jobs:
  include:
    - stage: unit tests
      script: ""
    - stage: unit tests
      script: ""
    - stage: deploy to staging
      script: skip
      deploy: &heroku
        provider: heroku
        app: version-engine-backoffice
        api_key: 246542ac-8051-4867-aa1b-89abe4fb5dc9
#    - stage: test staging
#      script: 'curl http://fsm-engine-backoffice-staging.herokuapp.com'
    - stage: deploy to production
      script: skip
      deploy:
        <<: *heroku
        app: version-engine-backoffice
    - stage: test production
      script: 'curl http://version-engine-backoffice.herokuapp.com'
